version: "3.7"

services:
  nexus_web:
    # Substitua pela sua imagem publicada no registry
    # Ex.: registry.example.com/nexus-agents:beta
    image: registry.example.com/nexus-agents:beta
    environment:
      - NODE_ENV=production
      - LOG_LEVEL=error
      - PORT=3000
      # Recomendo definir estas variáveis via Portainer (Environment/Secrets)
      - NEXT_PUBLIC_SUPABASE_URL=${NEXT_PUBLIC_SUPABASE_URL}
      - NEXT_PUBLIC_SUPABASE_ANON_KEY=${NEXT_PUBLIC_SUPABASE_ANON_KEY}
      - SUPABASE_SERVICE_ROLE_KEY=${SUPABASE_SERVICE_ROLE_KEY}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - WHATSAPP_WEBHOOK_API_KEY=${WHATSAPP_WEBHOOK_API_KEY}
    networks:
      - network_public
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          # Ajuste conforme necessário; exemplo fixa em linux
          - node.platform.os == linux
          # - node.hostname == host02
          # - node.role == worker
      resources:
        limits:
          cpus: "1.0"
          memory: 1024M
      labels:
        - traefik.enable=true
        # Router HTTPS
        - traefik.http.routers.nexus.rule=Host(`app.seu-dominio.com.br`)
        - traefik.http.routers.nexus.entrypoints=websecure
        - traefik.http.routers.nexus.tls.certresolver=le
        # Serviço (porta interna do container)
        - traefik.http.services.nexus.loadbalancer.server.port=3000
        - traefik.http.services.nexus.loadbalancer.passHostHeader=true
        # (Opcional) Middlewares
        # - traefik.http.middlewares.nexus-ratelimit.ratelimit.average=100
        # - traefik.http.middlewares.nexus-ratelimit.ratelimit.burst=50
        # - traefik.http.routers.nexus.middlewares=nexus-ratelimit
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

networks:
  network_public:
    external: true
    name: network_public
