version: "3.9"
services:
  nexus-web:
    image: docker.io/frmilani/nexus-agents:beta
    #env_file:
      # Opcional: use um arquivo .env específico para o Swarm (não versionado)
      # - .env.swarm
    environment:
      NODE_ENV: production
      LOG_LEVEL: info
      # CONFIG PÚBLICO em runtime (exposto ao client via /api/public-config -> window.__PUBLIC_CONFIG__)
      SUPABASE_URL: "URL"
      SUPABASE_ANON_KEY: "CHAVE"
      # SEGREDOS SOMENTE NO SERVIDOR (não expostos ao client)
      OPENAI_API_KEY: "COLOQUE_NO_PORTAINER_COMO_SECRET_SE_POSSIVEL"
      WEBHOOK_URL: "URL"
      WEBHOOK_API_KEY: "CHAVE"
      # Outras variáveis necessárias ao servidor (service role NUNCA vai para o cliente)
      # SUPABASE_SERVICE_ROLE_KEY: "COLOQUE_NO_PORTAINER_COMO_SECRET_SE_POSSIVEL"
    deploy:
      replicas: 1
      #placement:
      #  constraints:
      #    - node.role == manager
      update_config:
        order: start-first
        parallelism: 1
        delay: 5s
      restart_policy:
        condition: on-failure
      labels:        
        
        - traefik.enable=true # habilita o traefik        
        - traefik.http.routers.nexus-web.rule=Host(`SEU DOMINIO`)        
        - traefik.http.routers.nexus-web.entrypoints=websecure
        - traefik.http.routers.nexus-web.tls.certresolver=letsencryptresolver        
        - traefik.http.routers.nexus-web.service=nexus-web        
        - traefik.http.services.nexus-web.loadbalancer.server.port=3000
        - traefik.http.services.nexus-web.loadbalancer.passhostheader=true        
        - traefik.http.middlewares.sslheader.headers.customrequestheaders.X-Forwarded-Proto=https
        - traefik.http.routers.chatwoot_app.middlewares=sslheader@docker
    networks:
      - network_public
    healthcheck:
      test: ["CMD", "sh", "-c", "wget -qO- http://127.0.0.1:3000/api/health >/dev/null 2>&1 || exit 1"]
      interval: 20s
      timeout: 5s
      retries: 5
      start_period: 60s
    # Sem ports: Traefik fará o proxy via labels

networks:
  network_public:
    external: true
    name: network_public